// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrupoExito.iOS.Views
{
	public partial class Home : UIView
	{
		public Home (IntPtr handle) : base (handle)
		{
		}
	}
}
