// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrupoExito.iOS.Views
{
	public partial class RegisterUserViewController : UIViewController
	{
		public RegisterUserViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
