package co.gov.and.coronapp.bluetrace.bluetooth.gatt

import co.gov.and.coronapp.bluetrace.BuildConfig

const val ACTION_RECEIVED_STREETPASS = "${BuildConfig.APPLICATION_ID}.ACTION_RECEIVED_STREETPASS"
const val ACTION_RECEIVED_STATUS = "${BuildConfig.APPLICATION_ID}.ACTION_RECEIVED_STATUS"
const val ACTION_RECEIVED_TEMPORARY_ID = "${BuildConfig.APPLICATION_ID}.ACTION_RECEIVED_TEMPORARY_ID"
const val ACTION_RECEIVED_MESSAGE = "${BuildConfig.APPLICATION_ID}.ACTION_RECEIVED_MESSAGE"

const val STREET_PASS = "${BuildConfig.APPLICATION_ID}.STREET_PASS"
const val STREET_PASS_RECORD = "${BuildConfig.APPLICATION_ID}.STREET_PASS_RECORD"
const val STATUS = "${BuildConfig.APPLICATION_ID}.STATUS"
const val TEMPORARY_ID = "${BuildConfig.APPLICATION_ID}.TEMPORARY_ID"
const val MESSAGE = "${BuildConfig.APPLICATION_ID}.MESSAGE"

const val DEVICE_ADDRESS = "${BuildConfig.APPLICATION_ID}.DEVICE_ADDRESS"
const val CONNECTION_DATA = "${BuildConfig.APPLICATION_ID}.CONNECTION_DATA"
const val ACTION_DEVICE_PROCESSED = "${BuildConfig.APPLICATION_ID}.ACTION_DEVICE_PROCESSED"

