// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrupoExito.iOS.ViewControllers.ReusableControllers
{
	public partial class CustomScrollView : UIScrollView
	{
		public CustomScrollView (IntPtr handle) : base (handle)
		{
		}

        public override bool TouchesShouldCancelInContentView(UIView view)
        {
            if (!(view is UITextField) && !(view is UISlider) && !(view is UISwitch))
            {
                return true;
            }
            else return false;
        }
    }
}
