//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoExito.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppConfigurations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppConfigurations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrupoExito.Utilities.Resources.AppConfigurations", typeof(AppConfigurations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2c459991-ba4f-4aa9-ad84-6ac3784d19de.
        /// </summary>
        public static string AndroidAppCenterId {
            get {
                return ResourceManager.GetString("AndroidAppCenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyA0-XV1TDnb3EZ_tmnLdNfVwqfcrZuO31g.
        /// </summary>
        public static string ApiKeyGoogle {
            get {
                return ResourceManager.GetString("ApiKeyGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyAhTbIbC61Aj-T2Ex8NM8mzY-j811uXaY8.
        /// </summary>
        public static string ApiKeyGoogleMapsIos {
            get {
                return ResourceManager.GetString("ApiKeyGoogleMapsIos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carulla.
        /// </summary>
        public static string AppNotificationTitle {
            get {
                return ResourceManager.GetString("AppNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://itunes.apple.com/us/app/carulla/id1437277351?l=es&amp;ls=1&amp;mt=8.
        /// </summary>
        public static string AppStoreUrlCarulla {
            get {
                return ResourceManager.GetString("AppStoreUrlCarulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://itunes.apple.com/us/app/%C3%A9xito/id1437270443?l=es&amp;ls=1&amp;mt=8.
        /// </summary>
        public static string AppStoreUrlExito {
            get {
                return ResourceManager.GetString("AppStoreUrlExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes a domingo de 7:00 a.m a 9:00 p.m.
        /// </summary>
        public static string AttentionSchedule {
            get {
                return ResourceManager.GetString("AttentionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string CashDrawer {
            get {
                return ResourceManager.GetString("CashDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///            {  
        ///                &quot;Name&quot;:&quot;Bogotá:&quot;,
        ///                &quot;Number&quot;:&quot;031 745 5777&quot;
        ///            },
        ///              {  
        ///                &quot;Name&quot;:&quot;Medellín:&quot;,
        ///                &quot;Number&quot;:&quot;034 604 4250&quot;
        ///            },
        ///              {  
        ///                &quot;Name&quot;:&quot;Cali:&quot;,
        ///                &quot;Number&quot;:&quot;032 489 0555&quot;
        ///            },
        ///              {  
        ///                &quot;Name&quot;:&quot;Barranquilla:&quot;,
        ///                &quot;Number&quot;:&quot;035 311 7888&quot;
        ///            },
        ///              {  
        ///                &quot;Name&quot;:&quot;Cartagena:&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactsSourceCarulla {
            get {
                return ResourceManager.GetString("ContactsSourceCarulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///          {  
        ///              &quot;Name&quot;:&quot;Bogotá:&quot;,
        ///              &quot;Number&quot;:&quot;031 745 5444&quot;
        ///          },
        ///            {  
        ///              &quot;Name&quot;:&quot;Medellín:&quot;,
        ///              &quot;Number&quot;:&quot;034 604 1919&quot;
        ///          },
        ///            {  
        ///              &quot;Name&quot;:&quot;Cali:&quot;,
        ///              &quot;Number&quot;:&quot;032 489 1222&quot;
        ///          },
        ///            {  
        ///              &quot;Name&quot;:&quot;Barranquilla:&quot;,
        ///              &quot;Number&quot;:&quot;035 311 7979&quot;
        ///          },
        ///            {  
        ///              &quot;Name&quot;:&quot;Cartagena:&quot;,
        ///              &quot;Number&quot;:&quot;035 694 5959&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactsSourceExito {
            get {
                return ResourceManager.GetString("ContactsSourceExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colombia.
        /// </summary>
        public static string CountryGeolocation {
            get {
                return ResourceManager.GetString("CountryGeolocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///      &quot;Text&quot;: &quot;Día&quot;
        ///    },
        ///    {
        ///     &quot;Text&quot;: &quot;1&quot;
        ///    },
        ///	{
        ///     &quot;Text&quot;: &quot;2&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;3&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;4&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;5&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;6&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;7&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;8&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;9&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;10&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;11&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;12&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;13&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;14&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;15&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;16 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DaysSource {
            get {
                return ResourceManager.GetString("DaysSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000.
        /// </summary>
        public static string DefaultCellphone {
            get {
                return ResourceManager.GetString("DefaultCellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([\w\.\-]+)@([\w\-]+)((\.(\w){2,})+)$.
        /// </summary>
        public static string EmailRegularExpression {
            get {
                return ResourceManager.GetString("EmailRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z5hXiJ92jMsMBCggnUsKIg==.
        /// </summary>
        public static string EncrypKey {
            get {
                return ResourceManager.GetString("EncrypKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.exito.com.
        /// </summary>
        public static string Exitoprime {
            get {
                return ResourceManager.GetString("Exitoprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34d0432a-f132-4d9b-baea-9da07d3427b3.
        /// </summary>
        public static string IOSAppCenterId {
            get {
                return ResourceManager.GetString("IOSAppCenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint=sb://notificationappcarulladev.servicebus.windows.net/;SharedAccessKeyName=DefaultListenSharedAccessSignature;SharedAccessKey=sOIF0TwESONAufwLB3qqD7NNE+aQep4v1xEelupLjqI=.
        /// </summary>
        public static string ListenConnectionString {
            get {
                return ResourceManager.GetString("ListenConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to market://details?id=.
        /// </summary>
        public static string MarketUrl {
            get {
                return ResourceManager.GetString("MarketUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string MaxActiveDiscounts {
            get {
                return ResourceManager.GetString("MaxActiveDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///        &quot;icon&quot;:&quot;compras&quot;,
        ///        &quot;title&quot;:&quot;Hacer mis compras&quot;,
        ///        &quot;actionName&quot;:&quot;Purchases&quot;,
        ///        &quot;Horizontal&quot;:true
        ///    },
        ///    {
        ///        &quot;icon&quot;:&quot;sticker_inicio&quot;,
        ///        &quot;title&quot;:&quot;Stickers&quot;,
        ///        &quot;actionName&quot;:&quot;Stickers&quot;,
        ///        &quot;Horizontal&quot;:true
        ///    },
        ///    {
        ///        &quot;icon&quot;:&quot;mi_descuento_primario&quot;,
        ///        &quot;title&quot;:&quot;Mi Descuento&quot;,
        ///        &quot;actionName&quot;:&quot;Discounts&quot;,
        ///        &quot;Horizontal&quot;:true
        ///    },
        ///    {
        ///        &quot;icon&quot;:&quot;servicios_almacen&quot;,
        ///        &quot;title&quot;:&quot;Servicios almacén&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MenuLobbySource {
            get {
                return ResourceManager.GetString("MenuLobbySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;icon&quot;:&quot;pedidos&quot;,
        ///        &quot;iconGray&quot;:&quot;pedidos_primario&quot;,
        ///        &quot;iconBlue&quot;:&quot;pedidos_terciario&quot;,
        ///        &quot;title&quot;:&quot;Mis pedidos&quot;,
        ///        &quot;subtitle&quot;:&quot;&quot;,
        ///        &quot;actionName&quot;:&quot;MyOrders&quot;,
        ///        &quot;quantity&quot;:0
        ///    },
        ///    {
        ///        &quot;icon&quot;:&quot;direcciones&quot;,
        ///        &quot;iconGray&quot;:&quot;direcciones_primario&quot;,
        ///        &quot;iconBlue&quot;:&quot;direcciones_terciario&quot;,
        ///        &quot;title&quot;:&quot;Mis direcciones&quot;,
        ///        &quot;subtitle&quot;:&quot;&quot;,
        ///        &quot;actionName&quot;:&quot;MyAddresses&quot;,
        ///        &quot;quantity&quot;:0
        ///    },
        ///    {
        ///        &quot;icon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MenuMyAccountSource {
            get {
                return ResourceManager.GetString("MenuMyAccountSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///   {  
        ///      &quot;icon&quot;:&quot;consultar_soat&quot;,
        ///      &quot;title&quot;:&quot;Consulta SOAT digital&quot;,
        ///      &quot;subtitle&quot;:&quot;Tu SOAT es ahora un documento en versión digital&quot;,
        ///      &quot;actionName&quot;:&quot;Soat&quot;,
        ///   }
        ///].
        /// </summary>
        public static string MenuOtherServicesSource {
            get {
                return ResourceManager.GetString("MenuOtherServicesSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///   {  
        ///      &quot;icon&quot;:&quot;mi_descuento&quot;,
        ///      &quot;title&quot;:&quot;Mi Descuento&quot;,
        ///      &quot;subtitle&quot;:&quot;Activa tus cupones y redímelos en el almacén&quot;,
        ///      &quot;actionName&quot;:&quot;Discounts&quot;,
        ///   },
        ///   {  
        ///      &quot;icon&quot;:&quot;solicitar_turno_caja&quot;,
        ///      &quot;title&quot;:&quot;Solicita turno en caja&quot;,
        ///      &quot;subtitle&quot;:&quot;Solicita fácilmente tu turno en caja&quot;,
        ///      &quot;actionName&quot;:&quot;CashDrawerTurn&quot;,      
        ///   },   
        ///   {  
        ///      &quot;icon&quot;:&quot;chequeo_precios&quot;,
        ///      &quot;title&quot;:&quot;Chequea tus productos&quot;,
        ///      &quot;subtitle&quot;:&quot;Chequea el precio de los productos [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MenuServicesInStoreSource {
            get {
                return ResourceManager.GetString("MenuServicesInStoreSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3[0-9][0-9].
        /// </summary>
        public static string MobilePhoneFormat {
            get {
                return ResourceManager.GetString("MobilePhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///      &quot;Text&quot;: &quot;Mes&quot;
        ///    },
        ///    {
        ///     &quot;Text&quot;: &quot;1&quot;
        ///    },
        ///	{
        ///     &quot;Text&quot;: &quot;2&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;3&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;4&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;5&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;6&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;7&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;8&quot;
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;9&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;10&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;11&quot; 
        ///	}, 
        ///	{
        ///      &quot;Text&quot;: &quot;12&quot; 
        ///	}
        ///].
        /// </summary>
        public static string MonthsSource {
            get {
                return ResourceManager.GetString("MonthsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification_AppCarulla_Dev.
        /// </summary>
        public static string NotificationHubName {
            get {
                return ResourceManager.GetString("NotificationHubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9.]+$.
        /// </summary>
        public static string NumberMoreLetterRegularExpression {
            get {
                return ResourceManager.GetString("NumberMoreLetterRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string NumberOfPageSticker {
            get {
                return ResourceManager.GetString("NumberOfPageSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://play.google.com/store/apps/details?id=.
        /// </summary>
        public static string PlayStoreUrl {
            get {
                return ResourceManager.GetString("PlayStoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.exito.com/prime.
        /// </summary>
        public static string PurchasePrime {
            get {
                return ResourceManager.GetString("PurchasePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.com.
        /// </summary>
        public static string ReachableUrl {
            get {
                return ResourceManager.GetString("ReachableUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///   { 
        ///      &quot;title&quot;:&quot;Cantidad de productos&quot;,
        ///      &quot;value&quot;:&quot;10&quot;,
        ///      &quot;action&quot;:&quot;none&quot;,
        ///   },
        ///   { 
        ///      &quot;title&quot;:&quot;Dirección de envio&quot;,
        ///      &quot;value&quot;:&quot;calle 9 sur &quot;,
        ///      &quot;action&quot;:&quot;none&quot;,
        ///   },
        ///   { 
        ///      &quot;title&quot;:&quot;Medio de pago&quot;,
        ///      &quot;value&quot;:&quot;Efectivo&quot;,
        ///      &quot;action&quot;:&quot;none&quot;,
        ///   },
        ///   { 
        ///      &quot;title&quot;:&quot;Horario programado&quot;,
        ///      &quot;value&quot;:&quot;10:00 - 11:00&quot;,
        ///      &quot;action&quot;:&quot;none&quot;,
        ///   },
        ///            { 
        ///      &quot;title&quot;:&quot;Subtotal&quot;,
        ///      &quot;value&quot;:&quot;10.000&quot;,
        ///      &quot;action&quot;:&quot;none&quot;,
        ///   },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResumePurchaseSummary {
            get {
                return ResourceManager.GetString("ResumePurchaseSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slot_display_name.
        /// </summary>
        public static string SlotDisplayName {
            get {
                return ResourceManager.GetString("SlotDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 899970.
        /// </summary>
        public static string SmsOriginator {
            get {
                return ResourceManager.GetString("SmsOriginator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.exito.com/eventos/mecanicastikers.
        /// </summary>
        public static string TermsAndConditionStickers {
            get {
                return ResourceManager.GetString("TermsAndConditionStickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///      &quot;Title&quot;: &quot;¡Bienvenido!&quot;,
        ///      &quot;Description&quot;: &quot;Mercar cada vez es más sencillo: Compra tus productos favoritos, págalos fácil y recíbelos donde prefieras.&quot;
        ///    },
        ///    {
        ///      &quot;Title&quot;: &quot;¡Bienvenido!&quot;,
        ///      &quot;Description&quot;: &quot;Un lugar creado especialmente para ti, pensado en tus gustos y preferencias. Una app para servirte&quot;
        ///    },
        ///	{
        ///      &quot;Title&quot;: &quot;¡Bienvenido!&quot;,
        ///      &quot;Description&quot;: &quot;Servicio personalizado y ajustado a tus necesidades en un solo lugar, tanto para tus compras online co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextGalleryWelcomeSource {
            get {
                return ResourceManager.GetString("TextGalleryWelcomeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticket_name.
        /// </summary>
        public static string TicketNameDataValue {
            get {
                return ResourceManager.GetString("TicketNameDataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string TicketTimerTime {
            get {
                return ResourceManager.GetString("TicketTimerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Name&quot;:&quot;TutorialHome&quot;,
        ///        &quot;ImagesTutorial&quot;:[
        ///            {
        ///                &quot;urlImage&quot;:&quot;tutorial_home&quot;
        ///            },
        ///            {
        ///                &quot;urlImage&quot;:&quot;tutorial_buscar_agregar&quot;
        ///            },
        ///            
        ///            {
        ///                &quot;urlImage&quot;:&quot;tutorial_peso_variable&quot;
        ///            }
        ///        ]
        ///    },
        ///    {
        ///        &quot;Name&quot;:&quot;TutorialWelcome&quot;,
        ///        &quot;ImagesTutorial&quot;:[
        ///            {
        ///                &quot;urlImage&quot;:&quot;tutorial_entrega&quot;
        ///            }
        ///        ]
        ///    }
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TutorialsItem {
            get {
                return ResourceManager.GetString("TutorialsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to market://details?id=com.waze.
        /// </summary>
        public static string WazeStoreAndroidEndPoint {
            get {
                return ResourceManager.GetString("WazeStoreAndroidEndPoint", resourceCulture);
            }
        }
    }
}
