//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoExito.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppServiceConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppServiceConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrupoExito.Utilities.Resources.AppServiceConfiguration", typeof(AppServiceConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/myDiscount/activeEvent.
        /// </summary>
        public static string ActiveDiscountEndPoint {
            get {
                return ResourceManager.GetString("ActiveDiscountEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/.
        /// </summary>
        public static string AddAddressEndPoint {
            get {
                return ResourceManager.GetString("AddAddressEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://d3lvyp0t4faw4d.cloudfront.net/?userId={0}&amp;typeForm=saveCreditCard&amp;siteId={1}.
        /// </summary>
        public static string AddCreditCardEndPoint {
            get {
                return ResourceManager.GetString("AddCreditCardEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://d3vqko090al8sp.cloudfront.net/?uid={0}&amp;email={1}&amp;skin={2}.
        /// </summary>
        public static string AddCreditCardPaymentezEndPoint {
            get {
                return ResourceManager.GetString("AddCreditCardPaymentezEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/action=addItem.
        /// </summary>
        public static string AddProductShoppingListEndPoint {
            get {
                return ResourceManager.GetString("AddProductShoppingListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/action=addAllToCart.
        /// </summary>
        public static string AddProductsToCarEndPoint {
            get {
                return ResourceManager.GetString("AddProductsToCarEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/action=create.
        /// </summary>
        public static string AddShoppingListEndPoint {
            get {
                return ResourceManager.GetString("AddShoppingListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xozt3bK4Ug/ZOpu8L7ZM14cZ297plgmwvhLFALpXHl9cq2RRhfEibTOnx9YhoqvS.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://appmicompaniaqagrupoexito.azure-api.net/QA-.
        /// </summary>
        public static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMasters/api/v2/app/version/os/{0}.
        /// </summary>
        public static string AppVersionEndPoint {
            get {
                return ResourceManager.GetString("AppVersionEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://maps.googleapis.com/maps/api/place/autocomplete/json?input={0}&amp;types=geocode&amp;language=es_CO&amp;key={1}.
        /// </summary>
        public static string AutocompleteAddressEndPoint {
            get {
                return ResourceManager.GetString("AutocompleteAddressEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/ticket/cancel.
        /// </summary>
        public static string CancelTicketEndPoint {
            get {
                return ResourceManager.GetString("CancelTicketEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMasters/api/v1/productCategories/.
        /// </summary>
        public static string CategoriesEndPoint {
            get {
                return ResourceManager.GetString("CategoriesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMasters/api/v1/productCategories/.
        /// </summary>
        public static string CategoriesEndPoint1 {
            get {
                return ResourceManager.GetString("CategoriesEndPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents/api/v1/categories.
        /// </summary>
        public static string CategoryOfRecipesEndPoint {
            get {
                return ResourceManager.GetString("CategoryOfRecipesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/check/price/cities.
        /// </summary>
        public static string CheckerCitiesEndPoint {
            get {
                return ResourceManager.GetString("CheckerCitiesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/check/price/cities/{0}/dependecies.
        /// </summary>
        public static string CheckerDependenciesEndPoint {
            get {
                return ResourceManager.GetString("CheckerDependenciesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/check/price/coverage.
        /// </summary>
        public static string CheckerPriceCoverageEndPoint {
            get {
                return ResourceManager.GetString("CheckerPriceCoverageEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/check/price.
        /// </summary>
        public static string CheckerPriceEndPoint {
            get {
                return ResourceManager.GetString("CheckerPriceEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/coverage.
        /// </summary>
        public static string CoverageAddressEndPoint {
            get {
                return ResourceManager.GetString("CoverageAddressEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v2/products/dunnhumby.
        /// </summary>
        public static string CustomerProductsEndPoint {
            get {
                return ResourceManager.GetString("CustomerProductsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/addressKey={0}.
        /// </summary>
        public static string DeleteAddressEndPoint {
            get {
                return ResourceManager.GetString("DeleteAddressEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/card/bin={0}.
        /// </summary>
        public static string DeleteCreditCardEndPoint {
            get {
                return ResourceManager.GetString("DeleteCreditCardEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments/api/v1/cardClient/deleteCard.
        /// </summary>
        public static string DeleteCreditCardPaymentezEndPoint {
            get {
                return ResourceManager.GetString("DeleteCreditCardPaymentezEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/items/listId={0}&amp;itemId={1}.
        /// </summary>
        public static string DeleteProductShoppingListEndPoint {
            get {
                return ResourceManager.GetString("DeleteProductShoppingListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/listId={0}.
        /// </summary>
        public static string DeleteShoppingListEndPoint {
            get {
                return ResourceManager.GetString("DeleteShoppingListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/device.
        /// </summary>
        public static string DeviceCashDrawerTurnEndPoint {
            get {
                return ResourceManager.GetString("DeviceCashDrawerTurnEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v3/myDiscount/events.
        /// </summary>
        public static string DicountsEndPoint {
            get {
                return ResourceManager.GetString("DicountsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMasters/api/v1/documentTypes.
        /// </summary>
        public static string DocumentTypesEndPoint {
            get {
                return ResourceManager.GetString("DocumentTypesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/action=EmptyCart.
        /// </summary>
        public static string FlushCarEndPoint {
            get {
                return ResourceManager.GetString("FlushCarEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/action=getActiveOrderId.
        /// </summary>
        public static string GetActiveOrderEndPoint {
            get {
                return ResourceManager.GetString("GetActiveOrderEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/anonymous/refreshsession.
        /// </summary>
        public static string GetAnonymousRefreshTokenEndpoint {
            get {
                return ResourceManager.GetString("GetAnonymousRefreshTokenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/anonymous/session.
        /// </summary>
        public static string GetAnonymousTokenEndpoint {
            get {
                return ResourceManager.GetString("GetAnonymousTokenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/stickers/balance.
        /// </summary>
        public static string GetBalanceEndPoint {
            get {
                return ResourceManager.GetString("GetBalanceEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/action=getCities.
        /// </summary>
        public static string GetCitiesEndPoint {
            get {
                return ResourceManager.GetString("GetCitiesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/.
        /// </summary>
        public static string GetClientEndPoint {
            get {
                return ResourceManager.GetString("GetClientEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents/api/v1/sliders/city/{0}.
        /// </summary>
        public static string GetContentHomeEndPoint {
            get {
                return ResourceManager.GetString("GetContentHomeEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/card/.
        /// </summary>
        public static string GetCreditCardsEndPoint {
            get {
                return ResourceManager.GetString("GetCreditCardsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments/api/v1/cardClient/listCards.
        /// </summary>
        public static string GetCreditCardsPaymentezEndPoint {
            get {
                return ResourceManager.GetString("GetCreditCardsPaymentezEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/deviceId.
        /// </summary>
        public static string GetDeviceCashDrawerTurnEndPoint {
            get {
                return ResourceManager.GetString("GetDeviceCashDrawerTurnEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v2/client/session.
        /// </summary>
        public static string GetLoginEndpoint {
            get {
                return ResourceManager.GetString("GetLoginEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/historical/detail.
        /// </summary>
        public static string GetOrderHistoricalEndPoint {
            get {
                return ResourceManager.GetString("GetOrderHistoricalEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/dependencies/action=getDependencySchedules.
        /// </summary>
        public static string GetOrderSchedulesEndPoint {
            get {
                return ResourceManager.GetString("GetOrderSchedulesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders.
        /// </summary>
        public static string GetOrdersEndPoint {
            get {
                return ResourceManager.GetString("GetOrdersEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/tracking.
        /// </summary>
        public static string GetOrderTrackingEndPoint {
            get {
                return ResourceManager.GetString("GetOrderTrackingEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/products/action=prices.
        /// </summary>
        public static string GetProductsPriceEndPoint {
            get {
                return ResourceManager.GetString("GetProductsPriceEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/items/listId={0}.
        /// </summary>
        public static string GetProductsShoppingListEndPoint {
            get {
                return ResourceManager.GetString("GetProductsShoppingListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/refreshsession.
        /// </summary>
        public static string GetRefreshTokenEndpoint {
            get {
                return ResourceManager.GetString("GetRefreshTokenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/contingency.
        /// </summary>
        public static string GetScheduleContingencyEndPoint {
            get {
                return ResourceManager.GetString("GetScheduleContingencyEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMasters/api/v1/soat.
        /// </summary>
        public static string GetSoatEndPoint {
            get {
                return ResourceManager.GetString("GetSoatEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/segment.
        /// </summary>
        public static string GetUserTypeEndPoint {
            get {
                return ResourceManager.GetString("GetUserTypeEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/myDiscount/InactiveEvent.
        /// </summary>
        public static string InactiveDiscountEndPoint {
            get {
                return ResourceManager.GetString("InactiveDiscountEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7C-AD-D1-17-16-60-B8-42-19-A4-83-71-DE-66-8C-57-F5-79-E9-70-7E-3F-AA-1B-2F-AD-E1-94-AF-E4-58-21.
        /// </summary>
        public static string InnerStrength {
            get {
                return ResourceManager.GetString("InnerStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications/api/v1/notifications/Client.
        /// </summary>
        public static string NotificationsEndPoint {
            get {
                return ResourceManager.GetString("NotificationsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/action=checkout.
        /// </summary>
        public static string OrderProductCheckoutEndPoint {
            get {
                return ResourceManager.GetString("OrderProductCheckoutEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/historical.
        /// </summary>
        public static string OrdersHistoricalEndPoint {
            get {
                return ResourceManager.GetString("OrdersHistoricalEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z5hXiJ92jMsMBCggnUsKIg==.
        /// </summary>
        public static string OuterStrength {
            get {
                return ResourceManager.GetString("OuterStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/action=paymentSummary.
        /// </summary>
        public static string PaymentSummaryEndPoint {
            get {
                return ResourceManager.GetString("PaymentSummaryEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.carulla.com/images/category/app/tratamiento-datos-personales/carulla.html.
        /// </summary>
        public static string PersonalDataManagementUrl {
            get {
                return ResourceManager.GetString("PersonalDataManagementUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v2/products/action=detail.
        /// </summary>
        public static string ProductEndpoint {
            get {
                return ResourceManager.GetString("ProductEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v2/products/discount.
        /// </summary>
        public static string ProductsAppDiscountsEndPoint {
            get {
                return ResourceManager.GetString("ProductsAppDiscountsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/listId={0}.
        /// </summary>
        public static string ProductsShoppingListEndPoint {
            get {
                return ResourceManager.GetString("ProductsShoppingListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents/api/v1/content/{0}.
        /// </summary>
        public static string RecipeEndPoint {
            get {
                return ResourceManager.GetString("RecipeEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents/api/v1/categories/{0}/recipes.
        /// </summary>
        public static string RecipiesByCategoryEndPoint {
            get {
                return ResourceManager.GetString("RecipiesByCategoryEndPoint", resourceCulture);
            }
        }
        
        ///   Looks up a localized string similar to Contents/api/v1/promotions.
        /// </summary>
        public static string PromotionEndPoint {
            get {
                return ResourceManager.GetString("PromotionEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/password?email={0}.
        /// </summary>
        public static string RecoverPasswordEndpoint {
            get {
                return ResourceManager.GetString("RecoverPasswordEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v2/client.
        /// </summary>
        public static string RegisteClientEndPoint {
            get {
                return ResourceManager.GetString("RegisteClientEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/myDiscount/registerCustomer.
        /// </summary>
        public static string RegisterCostumerEndPoint {
            get {
                return ResourceManager.GetString("RegisterCostumerEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/correspondence/.
        /// </summary>
        public static string SaveCorrespondenceEndPoint {
            get {
                return ResourceManager.GetString("SaveCorrespondenceEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicKeys/api/v1/publickeys/client.
        /// </summary>
        public static string SaveKeyEndPoint {
            get {
                return ResourceManager.GetString("SaveKeyEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/reservation/.
        /// </summary>
        public static string ScheduleReservationEndPoint {
            get {
                return ResourceManager.GetString("ScheduleReservationEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v2/products/action=search.
        /// </summary>
        public static string SearchProductsEndpoint {
            get {
                return ResourceManager.GetString("SearchProductsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/sms.
        /// </summary>
        public static string SendMessageVerifyUserEndPoint {
            get {
                return ResourceManager.GetString("SendMessageVerifyUserEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/action=setDefaultAddress.
        /// </summary>
        public static string SetDefaultAddressEndPoint {
            get {
                return ResourceManager.GetString("SetDefaultAddressEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/action=setPaymentOnDelivery.
        /// </summary>
        public static string SetPaymentOnDeliveryEndPoint {
            get {
                return ResourceManager.GetString("SetPaymentOnDeliveryEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/.
        /// </summary>
        public static string ShoppingListsEndPoint {
            get {
                return ResourceManager.GetString("ShoppingListsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carulla.
        /// </summary>
        public static string SiteId {
            get {
                return ResourceManager.GetString("SiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/line/status.
        /// </summary>
        public static string StatusCashDrawerTurnEndPoint {
            get {
                return ResourceManager.GetString("StatusCashDrawerTurnEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/ticket/status.
        /// </summary>
        public static string StatusTicketEndPoint {
            get {
                return ResourceManager.GetString("StatusTicketEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMasters/api/v1/dependencies/.
        /// </summary>
        public static string StoreEndPoint {
            get {
                return ResourceManager.GetString("StoreEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/dependencies/action=getDependencies.
        /// </summary>
        public static string StoresByCityEndPoint {
            get {
                return ResourceManager.GetString("StoresByCityEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/sites.
        /// </summary>
        public static string StoresCashDrawerTurnEndPoint {
            get {
                return ResourceManager.GetString("StoresCashDrawerTurnEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/products/suggest.
        /// </summary>
        public static string SuggestedProductsEndPoint {
            get {
                return ResourceManager.GetString("SuggestedProductsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/products/action=suggest.
        /// </summary>
        public static string SuggestProductsEndpoint {
            get {
                return ResourceManager.GetString("SuggestProductsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/summary.
        /// </summary>
        public static string SummaryEndPoint {
            get {
                return ResourceManager.GetString("SummaryEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/taxs.
        /// </summary>
        public static string TaxBagEndPoint {
            get {
                return ResourceManager.GetString("TaxBagEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.carulla.com/static/carulla/terminosycondicionesapp/page.html.
        /// </summary>
        public static string TermsAndConditionApp {
            get {
                return ResourceManager.GetString("TermsAndConditionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/ticket.
        /// </summary>
        public static string TicketEndPoint {
            get {
                return ResourceManager.GetString("TicketEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/.
        /// </summary>
        public static string UpdateAddressEndPoint {
            get {
                return ResourceManager.GetString("UpdateAddressEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/cellphone.
        /// </summary>
        public static string UpdateCellPhoneEndPoint {
            get {
                return ResourceManager.GetString("UpdateCellPhoneEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/cashDrawerTurn/device.
        /// </summary>
        public static string UpdateDeviceCashDrawerTurnEndPoint {
            get {
                return ResourceManager.GetString("UpdateDeviceCashDrawerTurnEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/action=updateDispatchRegion.
        /// </summary>
        public static string UpdateDispatchRegionEndPoint {
            get {
                return ResourceManager.GetString("UpdateDispatchRegionEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/orders/action=updateOrderNote.
        /// </summary>
        public static string UpdateOrderNoteEndPoint {
            get {
                return ResourceManager.GetString("UpdateOrderNoteEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/action=updatePassword.
        /// </summary>
        public static string UpdatePasswordEndPoint {
            get {
                return ResourceManager.GetString("UpdatePasswordEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/items/quantity.
        /// </summary>
        public static string UpdateQuantityItemListEndPoint {
            get {
                return ResourceManager.GetString("UpdateQuantityItemListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/api/v1/lists/action=update.
        /// </summary>
        public static string UpdateShoppingListEndPoint {
            get {
                return ResourceManager.GetString("UpdateShoppingListEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/client/action=updateClient.
        /// </summary>
        public static string UpdateUserEndPoint {
            get {
                return ResourceManager.GetString("UpdateUserEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/users/.
        /// </summary>
        public static string UpdateVerifyUserEndPoint {
            get {
                return ResourceManager.GetString("UpdateVerifyUserEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/points/balance.
        /// </summary>
        public static string UserPointsEndPoint {
            get {
                return ResourceManager.GetString("UserPointsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/api/v1/myDiscount/coupons.
        /// </summary>
        public static string ValidateActivatedCouponsEndPoint {
            get {
                return ResourceManager.GetString("ValidateActivatedCouponsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/address/correspondence/.
        /// </summary>
        public static string ValidateCorrespondenceEndPoint {
            get {
                return ResourceManager.GetString("ValidateCorrespondenceEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/validate/reservation/.
        /// </summary>
        public static string ValidateScheduleReservationEndPoint {
            get {
                return ResourceManager.GetString("ValidateScheduleReservationEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAccess/api/v1/users/code/validation/.
        /// </summary>
        public static string VerifyUserEndPoint {
            get {
                return ResourceManager.GetString("VerifyUserEndPoint", resourceCulture);
            }
        }
    }
}
